### ISSUE TITLE
Encode unsigned ints provided as signed ints

### ISSUE THREAD

**Issue by Dev1an** [Flight-School/MessagePack#3] opened 2018-07-02 11:06 UTC
According to [the spec](https://github.com/msgpack/msgpack/blob/master/spec.md#serialization-type-to-format-conversion)

> If an object can be represented in multiple possible output formats, serializers SHOULD use the format which represents the data in the smallest number of bytes.

When I encode the number 128 like this `MessagePackEncoder().encode(128)` it encodes it as an Int 16 (<D1 80 00>) while it should be encoded as <CC 80>

**Comment by mattt** [comment] 2018-07-24 19:24
Hi, @Dev1an. I believe this is behaving as expected. `MessagePackEncoder` should automatically encode types using the smallest representation, as recommended by the specification.

The default type for an integer literal is `Int`. Because the 128 in `MessagePackEncoder().encode(128)` doesn't have an explicit type, this method call routes to the overload that takes an `Int` argument, which encodes a signed integer. The maximum positive number expressible by an 8-bit signed integer is 127. The smallest signed integer type that can represent 128 is an `Int16`, which is consistent with your result.

If you want to produce `<CC 80>`, you would need to explicitly pass an unsigned integer:

```swift
MessagePackEncoder().encode(128 as UInt) 
```

**Comment by Dev1an** [comment] 2018-07-24 19:39
I know that if you want to encode to <CC 80> using this library (in its current state), you have to write `.encode(128 as UInt)` (so we need to explicitly cast it to the smallest representation).
But the MsgPack spec states:
> serializers SHOULD use the format which represents the data in the smallest number of bytes.

In other words serializers/encoders MAY NOT have the ability to explicitly denote the byte representation. The serializer/encoder SHOULD always cast numbers to their smallest representation behind the screens.

So if I have
```
let x: Int32 = 5
MessagePackEncoder().encode(x)
```
The The int32 should be encoded as a UInt8

**Comment by Dev1an** [comment] 2018-07-24 19:41
The problem is, that if you are using this library to decode numbers that are encoded using an other application, you will have failures.

**Comment by mattt** [comment] 2018-07-24 19:45
Responding to your first reply, I believe you're understanding of the specification is incorrect.

MessagePack distinguishes between signed and unsigned numbers, so the smallest representation of the number 5 stored in an `Int32` is not `UInt8`, but rather `Int8`.

To your second point, I don't understand what you mean. Have you experienced failures using this library?

**Comment by Dev1an** [comment] 2018-07-24 20:08
Yes I experience failures using this library. Here is a very simple reproduction: https://github.com/Dev1an/msgpack-error-reproduction

To reproduce (using toolchain: `4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)`):
 - clone the repo: `git clone https://github.com/Dev1an/msgpack-error-reproduction`
 - run the tests: `swift test`

I encoded the following JSON using the online encoder on the official website:
 - go to https://msgpack.org
 - click try!
 - enter the following JSON: `{"compact":true,"schema":128}`
 - copy the MessagePack bytes in hex representation

**Comment by mattt** [comment] 2018-07-24 20:18
Thanks for taking the time to reproduce this, @Dev1an. I really appreciate it.

From your payload `<cc 80>` is the MessagePack representation of an 8-bit unsigned integer with value 128. You're attempting to decode an `Int` type, which is a signed integer type that's equivalent to either `Int64` or `Int32`, depending on your platform. You can't decode a signed integer from an unsigned integer, so a failure is expected. You could fix this in your example with the following change:

```swift
let schema: UInt
```

It's unhelpful to compare MessagePack with JSON in this case, because JSON treats numbers totally differently. This detail is lost in translation on the msgpack.org tool you're using for debugging, and may cause confusion if you're unaware of these differences.

**Comment by Dev1an** [comment] 2018-07-24 20:38
Hey @mattt, thanks for the quick response. I know that you cannot specify signed or unsigned numbers using JSON. That is why the MsgPack specification explicitly states that libraries implementing this spec, should automatically convert numbers from and to the smallest representation.

I know that when you change the type of schema to `UInt` the test passes. But that is just the point. Say you have an application (not written in swift) that encodes the following 2D points (denoted using JSON) to valid MsgPack messages.
 - `{"x": 3, "y": -8}`
 - `{"x": 576, "y": -812}`

And say you want to decode and read these points in a Swift application. How wil you declare your Point struct?
if you declare it using:
```swift
struct Point {
  let x: Int
  let y: Int
}
```
It doesn't work because of the way you deserialise your numbers.
I tried extensively but I cannot read these points using your library. And this has nothing todo with the fact that the points are encoded using javascript, a language that doesn't differentiate between signed or unsigned numbers. The MsgPack specification is written in such a way that it can be implemented in languages that do differentiate these kinds of numbers as well as in languages that don't.

The problem is that your library looks at the **type** of the number when encoding. Instead the library should look at the **number** itself and determine what the smallest the smallest representation is. Then encode the number according to this smallest representation an not according to the type of the number.

The same goes for decoding numbers. A swift `Int64` can be decoded from a message pack positive fixint, negative fixint, int 8/16/32/64 or uint 8/16/32/64. This is very clear in the following table (listed in the spec under `Deserialization: format to type conversion`)

<table>
  <tr><th>source formats</th><th>output type</th></tr>
  <tr><td>positive fixint, negative fixint, int 8/16/32/64 and uint 8/16/32/64</td><td>Integer</td></tr>
</table>

A number of a fixed type (for example `Int64` in swift) can be encoded using different MsgPack formats. That is because If an number can be represented in multiple possible output formats, serializers SHOULD use the format which represents the data in the smallest number of bytes. So depending on the size of **the actual** number (**not its type**), different numbers of the same type are encoded using different formats.

**Comment by mattt** [comment] 2018-07-24 22:14
Thanks for clarifying, @Dev1an.

Your original issue was about **encoding**. After reading through the specification again and looking at other implementations, I still believe that this library is encoding integers correctly. 

From the specification:

> If an object can be represented in multiple possible output formats, serializers SHOULD use the format which represents the data in the smallest number of bytes.

I find the words "object" and "data" to be ambiguous in this context. Because Swift is a type-safe language, I believe that the storage of the value is intrinsic to its identity as an object. In the implementation of `SingleValueEncoder`, I made the decision to encode explicitly-sized integer types according to their expected MessagePack format—even if the particular value they hold _could_ be represented by a smaller type. If someone goes out of their way to specify an explicit size in Swift, I think there's a good argument to be made that this information should be encoded into the representation.

`Int` and `UInt` are used to represent integers when the particular storage isn't important. In these cases, I made the decision to automatically encode according to the smallest size with the same signedness.

In both of these cases,  I believe that the library is within its rights to have this behavior, according to SHOULD as defined by [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt).

As such, I would move to close this issue in particular.

That said, I think that the current behavior for **decoding**, which concerns #2, should be changed. Because there is underdetermination in how numbers can be represented (a JavaScript implementation could be justified in encoding the number 128 as either a signed integer, unsigned integer, or floating-point), the decoder should be able to accommodate those different representations.

This general sentiment is echoed by the Robustness Principle:

> Be conservative in what you send, be liberal in what you accept

I propose that the `decode` method for integer types should be able to decode any number value if it can represent that number exactly. A similar change may be necessary for the floating-point numbers as well.

Would this change be acceptable to you, @Dev1an?

**Comment by Dev1an** [comment] 2018-07-24 22:50
Sorry I initially made two issues. But when we started talking on this thread, I forgot about the other one.

I see that we differ in opinions: you want to couple the Swift types with the MsgPack formats, I don't... Each approach has its advantages 👍 and disadvantages 👎. This is how I see them:
<table>
  <tr><th>Couple types</th><th>Use smallest format possible</th></tr>
  <tr><td>👍 The developer can derive type information from the encoded message</td><td>👎 The developer cannot derive the type from the encoded message</td></tr>
  <tr><td>👎 The encoded message takes more place (especially when it contains an array with a lot of small int16's)</td><td>👍 The encoded message is as small as possible</td></tr>
</table>

What if the you leave the choice to the developer? Just like with apple's JSON encoder and decoder you could allow the developer to configure the encoder. This way the developer can opt in or out for compression of numbers using a simple boolean property on the encoder (for example `encoder.compressNumbers = false`).

Of course you can do with your own library what you want. If you want to strictly couple the types: That is your decision to make. As long as we can properly decode MsgPacks that are encoded with other libraries ( like you suggest in #2 ) I'm happy 😀.

**Closed as completed** 2018-07-26 18:22 UTC

**Comment by mattt** [comment] 2018-07-26 18:25
As of f6da9a4, `Int` and `UInt` types automatically encode to their smallest representation. The behavior for any explicitly-sized types (like `Int32`) remains unchanged, other than that `UInt8` and `Int8` will now automatically use fixed size integers if they fall within that range. You can see a corresponding unit test here: https://github.com/Flight-School/MessagePack/blob/master/Tests/MessagePackTests/MessagePackEncodingTests.swift#L26-L28

**Comment by mattt** [comment] 2018-07-26 18:27
Thanks again for taking the time to have this discussion, @Dev1an. I'm very happy with where things ended up (the new implementation is more correct and shorter, too).
